### ISSUE TITLE
Add string .ThrowIfNullOrWhiteSpace()

### ISSUE THREAD

**Issue by JeanGatto** [mantinband/throw#41]
Add the option to validate the type of a string, for example:

```
string productName = ""; // or null or " "
productName.ThrowIfNullOrWhiteSpace();
```

and

```
string productName = ""; // or null or " "
productName.Throw().IfNullOrWhiteSpace();
```

**Comment by mantinband** [comment]
Hey @JeanGatto thanks for opening this issue!

This is available currently as following

```csharp
#nullable enable

string productName;
productName.Throw().IfWhiteSpace();
```

```csharp
#nullable enable

string? productName;
productName.ThrowIfNull().IfWhiteSpace();

string? productName;
productName!.Throw().IfWhiteSpace();
```

```csharp
#nullable disable

string productName;
productName.ThrowIfNull().IfWhiteSpace();
```

Since the library is supported only from .NET 6+, most of these projects will have nullable reference types feature enabled, making the null check redundant.

This is the reason why I've separated the null check from everything. If the object _can_ be null, then it must be the first check 👇🏼
![Throw 16](https://user-images.githubusercontent.com/39407673/158671197-420d2aa0-a0d5-4115-83f3-985e4e2f8441.png)

**Comment by JeanGatto** [comment]
Thanks man!
